### ISSUE TITLE
恩山过来的，请问qsdk的应该选哪一个？

### ISSUE THREAD

**Issue by bot2333** [yaya131/Openwrt_Beta#42]
找了全网没找到qsdk12内核的actions，烦请大佬指点，内存实在是不够用，不去自定义一下太难了

**Comment by yaya131** [comment]
> 找了全网没找到qsdk12内核的actions，烦请大佬指点，内存实在是不够用，不去自定义一下太难了

肯定没有呀，又不是完全开源

**Comment by bot2333** [comment]
好吧，谢谢大佬回复。我还以为ax6都停产多年了快到机生末期，该开源的也差不多开源了。
